# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(974, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stockEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.stockEdit.setGeometry(QtCore.QRect(71, 42, 113, 21))
        self.stockEdit.setObjectName("stockEdit")
        self.flagBtn = QtWidgets.QPushButton(self.centralwidget)
        self.flagBtn.setEnabled(False)
        self.flagBtn.setGeometry(QtCore.QRect(201, 43, 91, 21))
        self.flagBtn.setObjectName("flagBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 42, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.flagLabel = QtWidgets.QLabel(self.centralwidget)
        self.flagLabel.setGeometry(QtCore.QRect(322, 46, 341, 16))
        self.flagLabel.setObjectName("flagLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.startDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.startDateEdit.setGeometry(QtCore.QRect(104, 81, 110, 22))
        self.startDateEdit.setObjectName("startDateEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 81, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.endDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.endDateEdit.setGeometry(QtCore.QRect(294, 82, 110, 22))
        self.endDateEdit.setObjectName("endDateEdit")
        self.scopeCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.scopeCheck.setGeometry(QtCore.QRect(360, 123, 51, 16))
        self.scopeCheck.setObjectName("scopeCheck")
        self.startScopeSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.startScopeSpin.setGeometry(QtCore.QRect(83, 120, 50, 22))
        self.startScopeSpin.setDecimals(1)
        self.startScopeSpin.setMinimum(0.1)
        self.startScopeSpin.setMaximum(2.5)
        self.startScopeSpin.setSingleStep(0.1)
        self.startScopeSpin.setObjectName("startScopeSpin")
        self.startSlipSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.startSlipSpin.setGeometry(QtCore.QRect(82, 163, 62, 22))
        self.startSlipSpin.setDecimals(4)
        self.startSlipSpin.setMinimum(0.0)
        self.startSlipSpin.setMaximum(0.01)
        self.startSlipSpin.setSingleStep(0.0001)
        self.startSlipSpin.setProperty("value", 0.0)
        self.startSlipSpin.setObjectName("startSlipSpin")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(16, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 120, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.endScopeSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.endScopeSpin.setEnabled(False)
        self.endScopeSpin.setGeometry(QtCore.QRect(180, 120, 50, 22))
        self.endScopeSpin.setDecimals(1)
        self.endScopeSpin.setMinimum(0.1)
        self.endScopeSpin.setMaximum(2.5)
        self.endScopeSpin.setSingleStep(0.1)
        self.endScopeSpin.setObjectName("endScopeSpin")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(540, 70, 401, 111))
        self.listWidget.setObjectName("listWidget")
        self.widget = matplotlibWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 200, 951, 451))
        self.widget.setObjectName("widget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(17, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pwdEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwdEdit.setGeometry(QtCore.QRect(132, 10, 171, 21))
        self.pwdEdit.setObjectName("pwdEdit")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(319, 10, 91, 21))
        self.loginBtn.setObjectName("loginBtn")
        self.testingBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testingBtn.setEnabled(False)
        self.testingBtn.setGeometry(QtCore.QRect(440, 120, 81, 51))
        self.testingBtn.setObjectName("testingBtn")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(250, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stepScopeSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.stepScopeSpin.setEnabled(False)
        self.stepScopeSpin.setGeometry(QtCore.QRect(290, 119, 50, 22))
        self.stepScopeSpin.setDecimals(1)
        self.stepScopeSpin.setMinimum(0.1)
        self.stepScopeSpin.setMaximum(1.0)
        self.stepScopeSpin.setSingleStep(0.1)
        self.stepScopeSpin.setObjectName("stepScopeSpin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "주식 최적화 백테스팅"))
        self.label.setText(_translate("MainWindow", "종목 :"))
        self.flagBtn.setText(_translate("MainWindow", "분석 가능 여부"))
        self.label_2.setText(_translate("MainWindow", "=>"))
        self.flagLabel.setText(_translate("MainWindow", "가능 / 불가능(코스피 지수 : kospi, 코스닥 지수 : kosdaq)"))
        self.label_4.setText(_translate("MainWindow", "시작 일 :"))
        self.label_5.setText(_translate("MainWindow", "종료 일 :"))
        self.scopeCheck.setText(_translate("MainWindow", "범위"))
        self.label_6.setText(_translate("MainWindow", "Scope :"))
        self.label_7.setText(_translate("MainWindow", "Slippage :"))
        self.label_8.setText(_translate("MainWindow", "~"))
        self.label_10.setText(_translate("MainWindow", "MySQL 패스워드 :"))
        self.loginBtn.setText(_translate("MainWindow", "로그인"))
        self.testingBtn.setText(_translate("MainWindow", "백테스팅"))
        self.label_12.setText(_translate("MainWindow", "간격"))


from ui.matplotlibWidgetFile import matplotlibWidget
